#%RAML 0.8
title: "mod-kb-ebsco"
baseUri: https://github.com/folio-org/mod-kb-ebsco
version: v1

documentation:
  - title: mod-kb-ebsco (category)
    content: Implements the eholdings interface using the EBSCO kb as a backend.


/eholdings/vendors:
  displayName: Vendors
